# Generated by Django 4.2.8 on 2023-12-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_by',
        ),
    ]
